site_name: TALISES Documentation
site_url: https://sascha.vowe.eu/talises-doc/
repo_url: https://github.com/savowe/talises-doc/
edit_uri: blob/master/docs/
site_author: Sascha Vowe
markdown_extensions:
  - toc
nav:
  - Home: 'index.md'
  - Installation: 'installation.md'
  - User Guide:
    - Generating a wave-function: 'user-guide/generating_a_wave-function.md'
    - Handling binary data: 'user-guide/handling_binary_data.md'
    - Propagate the wave-function: 'user-guide/time-propagation.md'
  - Examples:
    - Potential barrier: 'user-guide/examples/potential_barrier.md'
    - Atom interferometry in 1D harmonic trap: 'user-guide/examples/1D_harmonic_trap.md'
    - Momentum transfer in 2D harmonic trap: 'user-guide/examples/2D_harmonic_trap.md'
    - Stimulated Raman transitions: 'user-guide/examples/Raman_transitions.md'
    - Bose-Einstein condensate collision: 'user-guide/examples/BEC_scattering.md'
  - About:
    - License: 'about/license.md'

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML
theme:
  name: null
  custom_dir: cinder
  highlightjs: true
  colorscheme: github
