site_name: TALISES Documentation
site_url: https://sascha.vowe.eu/talises-doc/
repo_url: https://github.com/savowe/talises-doc/
edit_uri: blob/master/docs/
site_author: Sascha Vowe

nav:
  - Home: 'index.md'
  - Installation: 'installation.md'
  - User Guide:
    - Generating a wave-function: 'user-guide/generating_a_wave-function.md'
    - Handling binary data: 'user-guide/handling_binary_data.md'
    - Time-propagation: 'user-guide/time-propagation.md'
    - Examples:
      - Rabi Oscillations: 'user-guide/examples/rabi_oscillations.md'
      - Momentum transfer in 2D: 'user-guide/examples/2D_momentum_transfer.md'
  - About:
    - License: 'about/license.md'

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML
theme: cinder